-- Drop tables if they exist to start fresh
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE reviews';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE banks';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create Banks Table
CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) NOT NULL UNIQUE,
    app_package_id VARCHAR2(100) UNIQUE
);

-- Create Reviews Table
CREATE TABLE reviews (
    review_id VARCHAR2(255) PRIMARY KEY,
    bank_id NUMBER,
    review_text CLOB,
    rating NUMBER(1),
    review_date DATE,
    sentiment_label VARCHAR2(20),
    sentiment_score NUMBER(10, 9),
    identified_themes VARCHAR2(4000),
    source VARCHAR2(50),
    CONSTRAINT fk_bank
        FOREIGN KEY (bank_id)
        REFERENCES banks(bank_id)
);

COMMIT;
